Feature: mogwai addendum — scalar-stream re-entry

  # Valid traversals whose current object is a SCALAR (values()/count()/a projected value).
  # The official suite exercises these step families over ELEMENTS, but not consistently in
  # scalar position. Each scenario is a combination we implemented for combinatorial
  # completeness. @gap:scalar-position marks the family for a possible gremlin-test PR.

  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_whereXisXgtX30XXX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").where(__.is(gt(30)))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[32].i |
      | d[35].i |

  @gap:scalar-position
  @Unsupported
  Scenario: g_V_hasLabelXpersonX_valuesXnameX_mapXtoUpperX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("name").map(__.toUpper())
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | MARKO |
      | VADAS |
      | JOSH |
      | PETER |

  @gap:scalar-position
  @Unsupported
  Scenario: g_V_hasLabelXpersonX_valuesXageX_mapXcountX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").map(__.count())
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[1].l |
      | d[1].l |
      | d[1].l |
      | d[1].l |

  @gap:scalar-position
  @Unsupported
  Scenario: g_V_hasLabelXpersonX_valuesXageX_chooseXidentityX_optionXbetween_youngX_optionXnone_oldX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").choose(__.identity()).option(between(26,30),__.constant("young")).option(Pick.none,__.constant("old"))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | young |
      | young |
      | old |
      | old |

  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_mathX_x2X
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").math("_ * 2")
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[58.0].d |
      | d[54.0].d |
      | d[64.0].d |
      | d[70.0].d |

  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_coalesceXisXgtX30XX_constantX0XX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").coalesce(__.is(gt(30)),__.constant(0))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[32].i |
      | d[35].i |
      | d[0].i |
      | d[0].i |

  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_unionXconstantXaX_constantXbXX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").union(__.constant("a"),__.constant("b"))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | a |
      | a |
      | a |
      | a |
      | b |
      | b |
      | b |
      | b |

  # A COLLAPSING arm of a BATCHING branch reduces over the branch's WHOLE input.
  #
  # This scenario used to assert the opposite — all four ages twice — with a comment claiming it
  # "matches the element-parent branch convention". It matched our convention, not the reference's:
  # `UnionStep extends BranchStep`, and `BranchStep.standardAlgorithm` injects every start at once
  # when any option contains a `Barrier`, so both arms see all four ages and the answer is the two
  # extremes. (`coalesce`/`optional` do NOT extend `BranchStep`, which is why their per-traverser
  # arms are right — see docs/2026-08-01-branch-arm-barrier-scope-plan.md §1.)
  @gap:scalar-position
  @Unsupported
  Scenario: g_V_hasLabelXpersonX_valuesXageX_unionXminX_maxX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").union(__.min(),__.max())
      """
    When iterated to list
    Then the result should be ordered
      | result |
      | d[27].i |
      | d[35].i |

  # The same fact with a cardinality-mixing pair: `min()` collapses to one row while `constant()`
  # is fed every start, so batching is visible in the ROW COUNT and not only in the values.
  @gap:scalar-position
  @Unsupported
  Scenario: g_V_hasLabelXpersonX_valuesXageX_unionXminX_constantX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").union(__.min(),__.constant(99))
      """
    When iterated to list
    Then the result should be ordered
      | result |
      | d[27].i |
      | d[99].i |
      | d[99].i |
      | d[99].i |
      | d[99].i |

  # A collapsed arm's traverser is freshly GENERATED by the reducing barrier, so it carries no
  # labels — `select("x")` after one drops it, exactly as the reference does, while the
  # cardinality-preserving arm keeps its own.
  @gap:scalar-position
  @Unsupported
  Scenario: g_V_asXxX_valuesXageX_unionXminX_identityX_selectXxX_count
    Given the modern graph
    And the traversal of
      """
      g.V().as("x").values("age").union(__.min(),__.identity()).select("x").count()
      """
    When iterated to list
    Then the result should be ordered
      | result |
      | d[4].l |

  # Slice: a nested value-branch inside an arm composes through the same consumer (lowerSteps
  # recursion) — union nested in union.
  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_unionXconstantXaX_unionXconstantXbX_constantXcXXX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").union(__.constant("a"),__.union(__.constant("b"),__.constant("c")))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | a |
      | a |
      | a |
      | a |
      | b |
      | b |
      | b |
      | b |
      | c |
      | c |
      | c |
      | c |

  # Slice: a re-source arm (V()/E() head) CROSS JOINs the graph per value inside the pushed
  # scalar child scope; a following count() reduces per input. Each age re-sources all 6
  # vertices → count 6 per input. The value is discarded by the re-source (GraphStep isStart
  # =false), exactly as at the tail.
  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_mapXV_countX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").map(__.V().count())
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[6].l |
      | d[6].l |
      | d[6].l |
      | d[6].l |

  # Slice: a re-source arm ending in a projection yields the projected values per input (one
  # input here, V(1) = marko), flat-mapped.
  @gap:scalar-position
  @Unsupported
  Scenario: g_VX1X_valuesXageX_flatMapXV_hasLabelXpersonX_valuesXnameXX
    Given the modern graph
    And the traversal of
      """
      g.V(1).values("age").flatMap(__.V().hasLabel("person").values("name"))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | marko |
      | vadas |
      | josh |
      | peter |

  # Slice: mixed-shape arms over a scalar parent (a constant scalar arm + a re-source element
  # arm) merge into a VariantStream — the same dynamic-tag shape the element parent produces.
  # A count() tail is shape-agnostic over the variant and keeps the assertion deterministic:
  # one input (V(1), age 29) → 1 scalar 'x' + 6 vertices = 7.
  @gap:scalar-position
  Scenario: g_VX1X_valuesXageX_unionXconstantXxX_VX_count
    Given the modern graph
    And the traversal of
      """
      g.V(1).values("age").union(__.constant("x"),__.V()).count()
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[7].l |

  # Slice: mixed-shape coalesce over a scalar (a scalar predicate arm + a re-source element
  # arm) → a VariantStream, ordinal-gated first-productive. is(gt 100) never fires for age 29,
  # so the input falls to V() → 6 vertices; count() over the variant = 6.
  @gap:scalar-position
  Scenario: g_VX1X_valuesXageX_coalesceXisXgtX100XX_VX_count
    Given the modern graph
    And the traversal of
      """
      g.V(1).values("age").coalesce(__.is(gt(100)),__.V()).count()
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[6].l |

  # Slice: optional() over a scalar with an element arm → a VariantStream (arm rows where
  # productive, else the value restored). V() is productive → 6 vertices; count() = 6.
  @gap:scalar-position
  @Unsupported
  Scenario: g_VX1X_valuesXageX_optionalXVX_count
    Given the modern graph
    And the traversal of
      """
      g.V(1).values("age").optional(__.V()).count()
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[6].l |

  # optional() with a SCALAR filter arm restores the dropped inputs → identity over the values (gt 30
  # pass through the arm; 27/29 miss and are restored). Lowers as coalesce(is(gt(30)), __.identity())
  # (`optionalArms`) — the filter arm keeps the value, the empty fallback restores it.
  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_optionalXisXgtX30XXX
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").optional(__.is(gt(30)))
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[27].i |
      | d[29].i |
      | d[32].i |
      | d[35].i |

  @gap:scalar-position
  Scenario: g_V_hasLabelXpersonX_valuesXageX_aggregateXaX_capXaX_unfold
    Given the modern graph
    And the traversal of
      """
      g.V().hasLabel("person").values("age").aggregate("a").cap("a").unfold()
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[29].i |
      | d[27].i |
      | d[32].i |
      | d[35].i |

  @gap:scalar-position
  @Unsupported
  Scenario: g_injectXstrX_splitX_X
    Given an empty graph
    And the traversal of
      """
      g.inject("a,b,c").split(",")
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | l[a,b,c] |

  @gap:scalar-position
  Scenario: g_injectX0X_V_count
    Given the modern graph
    And the traversal of
      """
      g.inject(0).V().count()
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[6].l |

  @gap:scalar-typed
  Scenario: g_injectXbiglongX
    Given an empty graph
    And the traversal of
      """
      g.inject(9007199254740993L)
      """
    When iterated to list
    Then the result should be unordered
      | result |
      | d[9007199254740993].l |
